import "./globals.css";
import { ToastContainer } from "react-toastify";
import { useRouter } from "next/navigation";
import { roboto } from "../utils/google-fonts/fonts";
import "react-toastify/dist/ReactToastify.css";
import Header from "./sections/header/page";
import FooterSection from "./sections/footer/page";

// export const metadata = {
//   title: "Home Page",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Page title</title>
      </head>
      <body
        className={`${roboto.className} relative mx-7 my-7 md:mx-9 lg:mx-11`}
      >
        <Header />
        {children}
        <ToastContainer />
        <FooterSection />
      </body>
    </html>
  );
}
