import "./globals.css";
import { ToastContainer } from "react-toastify";
import { roboto } from "../utils/google-fonts/fonts";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} relative mx-7 my-7 md:mx-9 lg:mx-11`}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
